-- ============================================================================
-- SUPABASE MIGRATION v2 — Jobs, Tags, Roles, Finance Adjustments, Notifications
-- Run in Supabase → SQL Editor (or `psql` against your Supabase postgres).
--
-- SAFETY:
--   * 100% additive — no DROP, no DELETE, no ALTER that removes data.
--   * Idempotent — safe to run more than once.
--   * Preserves every existing client, payment, note, margin entry, override.
--   * Migrates existing records into the new structure (see backfills below).
--
-- WHAT IT DOES
--   1. Creates `jobs` (Client 1 ── many Jobs). Every existing client gets one
--      default Job that absorbs that client's job-level fields (status,
--      address, scope_of_work, job_cost, total_due, amount_paid, balance).
--      Clients keep their contact info (name, phone, email, address).
--   2. Adds `payments.job_id`, `notes.job_id`, `finance_margin_entries.job_id`
--      and backfills them from each client's default job, so existing
--      financial/note records stay associated with the right Job.
--   3. Creates `tags` + `job_tags` (database-backed, case-insensitive unique).
--   4. Creates `app_users` (Normal User vs Admin roles for Google login).
--   5. Creates `finance_adjustments` (admin override audit trail).
--   6. Creates `notifications` (in-app).
--   7. Creates `activity_log` (admin audit trail — who did what, when).
--   8. Keeps legacy client-level finance cache columns in sync via triggers so
--      existing readers (PDF invoices, margin tracker, finance summary) keep
--      working while new UI reads aggregate from `jobs`.
--   9. Enables RLS on all NEW tables (no policies → no direct anon access;
--      the backend's service-role connection bypasses RLS, so the app keeps
--      working). Existing tables are left as-is to avoid production surprises.
-- ============================================================================

-- ============================================================================
-- 1. JOBS
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.jobs (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  status text not null default 'Prospect',
  address text default '',
  scope_of_work text default '',
  job_cost numeric default 0,
  total_due numeric default 0,
  amount_paid numeric default 0,
  balance numeric default 0,
  legacy_storage_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS idx_jobs_client ON public.jobs(client_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs(status);
CREATE INDEX IF NOT EXISTS idx_jobs_created_at ON public.jobs(created_at);

-- Backfill: one default Job per existing client that doesn't have one yet
-- (idempotent + self-healing). Every client's existing job-level data is
-- preserved on its default Job; `legacy_storage_key` keeps old photos/PDFs
-- reachable.
INSERT INTO public.jobs (
  client_id, name, status, address, scope_of_work, job_cost,
  total_due, amount_paid, balance, legacy_storage_key, created_at
)
SELECT
  c.id,
  c.name,
  COALESCE(NULLIF(TRIM(c.status), ''), 'Prospect'),
  COALESCE(c.address, ''),
  COALESCE(c.scope_of_work, ''),
  COALESCE(c.job_cost, 0),
  COALESCE(c.total_due, 0),
  COALESCE(c.amount_paid, 0),
  GREATEST(0, COALESCE(c.total_due, 0) - COALESCE(c.amount_paid, 0)), -- never a negative balance
  c.id::text,
  COALESCE(c.created_at, now())
FROM public.clients c
WHERE NOT EXISTS (SELECT 1 FROM public.jobs j WHERE j.client_id = c.id);

-- ============================================================================
-- 2. LINK EXISTING RECORDS TO JOBS
-- ============================================================================
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS job_id bigint;
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS job_id bigint;
ALTER TABLE public.finance_margin_entries ADD COLUMN IF NOT EXISTS job_id bigint;

UPDATE public.payments p
  SET job_id = j.id
  FROM public.jobs j
  WHERE j.client_id = p.client_id AND p.job_id IS NULL;

UPDATE public.notes n
  SET job_id = j.id
  FROM public.jobs j
  WHERE j.client_id = n.client_id AND n.job_id IS NULL;

UPDATE public.finance_margin_entries e
  SET job_id = j.id
  FROM public.jobs j
  WHERE j.client_id = e.client_id AND e.job_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_payments_job ON public.payments(job_id);
CREATE INDEX IF NOT EXISTS idx_notes_job ON public.notes(job_id);
CREATE INDEX IF NOT EXISTS idx_margin_entries_job ON public.finance_margin_entries(job_id);

-- Normalize any legacy negative job balances (overpaid jobs): balance is
-- never negative; the excess is represented as Overpayment/Credit instead.
UPDATE public.jobs
  SET balance = GREATEST(0, total_due - amount_paid)
  WHERE balance < 0;

-- ============================================================================
-- 3. TAGS (database-backed, case-insensitive unique)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tags_name_lower ON public.tags (lower(name));

CREATE TABLE IF NOT EXISTS public.job_tags (
  job_id bigint not null references public.jobs(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (job_id, tag_id)
);
CREATE INDEX IF NOT EXISTS idx_job_tags_tag ON public.job_tags(tag_id);

-- ============================================================================
-- 4. APP USERS (Normal User vs Admin)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.app_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text default '',
  google_id text,
  role text not null default 'user' check (role in ('admin','user')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  last_login_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_google_id ON public.app_users (google_id) WHERE google_id IS NOT NULL;

-- ============================================================================
-- 5. FINANCE ADJUSTMENTS (admin override audit trail)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.finance_adjustments (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  job_id bigint references public.jobs(id) on delete set null,
  record_type text not null,            -- 'payment' | 'expense' | 'total_due' | 'job_cost'
  record_id bigint,                     -- id of the underlying record (if any)
  field_name text default '',
  old_value numeric,
  new_value numeric,
  reason text default '',
  adjusted_by text default '',           -- email
  adjusted_by_name text default '',
  created_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS idx_finance_adjustments_job ON public.finance_adjustments(job_id);
CREATE INDEX IF NOT EXISTS idx_finance_adjustments_created ON public.finance_adjustments(created_at DESC);

-- ============================================================================
-- 6. NOTIFICATIONS (in-app)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint generated by default as identity primary key,
  type text not null,
  message text not null,
  entity_type text default 'job',
  entity_id bigint,
  client_id bigint,
  job_id bigint,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON public.notifications(created_at DESC);

-- ============================================================================
-- 6b. ACTIVITY LOG (admin "who did what" audit trail)
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.activity_log (
  id bigint generated by default as identity primary key,
  actor_email text not null,
  actor_name text default '',
  actor_role text default 'user',
  action text not null,
  method text default '',
  path text default '',
  summary text default '',
  created_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS idx_activity_log_created ON public.activity_log(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_log_actor ON public.activity_log(actor_email);

-- ============================================================================
-- 7. TRIGGERS — keep legacy client finance cache + job balances consistent
--    (new code reads aggregated from `jobs`; these keep old readers accurate)
-- ============================================================================

-- Payments → job amount_paid / balance (never negative balance)
CREATE OR REPLACE FUNCTION public.refresh_job_finance_from_payments() RETURNS trigger AS $$
DECLARE
  affected_job bigint;
BEGIN
  affected_job := COALESCE(NEW.job_id, OLD.job_id);
  IF affected_job IS NOT NULL THEN
    UPDATE public.jobs j SET
      amount_paid = COALESCE((SELECT SUM(p.amount) FROM public.payments p WHERE p.job_id = j.id), 0),
      balance = GREATEST(0, j.total_due - COALESCE((SELECT SUM(p.amount) FROM public.payments p WHERE p.job_id = j.id), 0))
    WHERE j.id = affected_job;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_payments_refresh_job ON public.payments;
CREATE TRIGGER trg_payments_refresh_job
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.refresh_job_finance_from_payments();

-- total_due change → recompute job balance (no negative balance)
CREATE OR REPLACE FUNCTION public.refresh_job_balance() RETURNS trigger AS $$
BEGIN
  NEW.balance := GREATEST(0, NEW.total_due - COALESCE((SELECT SUM(p.amount) FROM public.payments p WHERE p.job_id = NEW.id), 0));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_jobs_balance ON public.jobs;
CREATE TRIGGER trg_jobs_balance
  BEFORE UPDATE OF total_due ON public.jobs
  FOR EACH ROW EXECUTE FUNCTION public.refresh_job_balance();

-- Jobs → client-level finance cache (legacy readers stay correct)
CREATE OR REPLACE FUNCTION public.refresh_client_finance_cache() RETURNS trigger AS $$
DECLARE
  affected_client bigint;
BEGIN
  affected_client := COALESCE(NEW.client_id, OLD.client_id);
  IF affected_client IS NOT NULL THEN
    UPDATE public.clients c SET
      total_due = COALESCE((SELECT SUM(j.total_due) FROM public.jobs j WHERE j.client_id = c.id), 0),
      amount_paid = COALESCE((SELECT SUM(j.amount_paid) FROM public.jobs j WHERE j.client_id = c.id), 0),
      balance = GREATEST(0, COALESCE((SELECT SUM(j.balance) FROM public.jobs j WHERE j.client_id = c.id), 0)),
      job_cost = COALESCE((SELECT SUM(j.job_cost) FROM public.jobs j WHERE j.client_id = c.id), 0)
    WHERE c.id = affected_client;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_jobs_refresh_client ON public.jobs;
CREATE TRIGGER trg_jobs_refresh_client
  AFTER INSERT OR UPDATE OR DELETE ON public.jobs
  FOR EACH ROW EXECUTE FUNCTION public.refresh_client_finance_cache();

-- One-time refresh of the client cache (keeps it correct before any new edits)
UPDATE public.clients c SET
  total_due = COALESCE((SELECT SUM(j.total_due) FROM public.jobs j WHERE j.client_id = c.id), 0),
  amount_paid = COALESCE((SELECT SUM(j.amount_paid) FROM public.jobs j WHERE j.client_id = c.id), 0),
  balance = GREATEST(0, COALESCE((SELECT SUM(j.balance) FROM public.jobs j WHERE j.client_id = c.id), 0)),
  job_cost = COALESCE((SELECT SUM(j.job_cost) FROM public.jobs j WHERE j.client_id = c.id), 0);

-- ============================================================================
-- 8. ROW LEVEL SECURITY — new tables only. No policies are created, so the
--    anon/authenticated keys cannot read or write these tables directly; the
--    backend connects with the service role, which bypasses RLS. Authorization
--    is enforced in the Express middleware layer (roles).
--    (If you later wire Supabase Auth to the app, add policies here.)
-- ============================================================================
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_adjustments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- ROLLBACK (manual, only if you must undo this migration — read carefully):
--   These statements remove the v2 additions WITHOUT touching original data
--   (payments/notes/margin entries keep their legacy client_id links). Run
--   them one at a time in this order, and only after confirming the app is
--   stopped so no new job-scoped rows are written.
--
--   DROP TRIGGER IF EXISTS trg_jobs_refresh_client ON public.jobs;
--   DROP TRIGGER IF EXISTS trg_jobs_balance ON public.jobs;
--   DROP TRIGGER IF EXISTS trg_payments_refresh_job ON public.payments;
--   DROP TABLE IF EXISTS public.activity_log;
--   DROP TABLE IF EXISTS public.notifications;
--   DROP TABLE IF EXISTS public.finance_adjustments;
--   DROP TABLE IF EXISTS public.app_users;
--   DROP TABLE IF EXISTS public.job_tags;
--   DROP TABLE IF EXISTS public.tags;
--   ALTER TABLE public.finance_margin_entries DROP COLUMN IF EXISTS job_id;
--   ALTER TABLE public.notes DROP COLUMN IF EXISTS job_id;
--   ALTER TABLE public.payments DROP COLUMN IF EXISTS job_id;
--   DROP TABLE IF EXISTS public.jobs;
-- ============================================================================
