-- Run these in your Supabase SQL editor to add the new columns.
-- Safe to run on an existing database — IF NOT EXISTS prevents errors.

ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS scope_of_work text DEFAULT '';
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS job_cost numeric DEFAULT 0;

-- Also ensure the settings table exists (for company profile + logo storage)
CREATE TABLE IF NOT EXISTS public.settings (
  key text PRIMARY KEY,
  value text NOT NULL
);

-- Margin tracker expenses table
CREATE TABLE IF NOT EXISTS public.finance_margin_entries (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  client_name text default '',
  category text default 'Misc',
  project text default '',
  invoice_status text default 'Pending',
  amount numeric default 0,
  expense_type text default 'one-time',
  recurring boolean default false,
  expense_date timestamptz not null default now(),
  notes text default '',
  attachment_url text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Finance overrides table (for yearly metrics manual overrides)
CREATE TABLE IF NOT EXISTS public.finance_overrides (
  year int primary key,
  total_expected numeric default 0,
  total_received numeric default 0,
  total_remaining numeric default 0,
  total_clients int default 0,
  notes text,
  updated_at timestamptz not null default now()
);
