-- ============================================================================
-- SUPABASE MIGRATION v3 — Sales assignment, two tag kinds, line items,
-- note authors, per-user notifications
--
-- Run in Supabase → SQL Editor (or `psql`). 100% additive + idempotent.
-- NOTE: the app also applies these automatically on boot (api/db.js), so this
-- file is the auditable record of the same schema for manual runs.
-- ============================================================================

-- Two distinct tag systems: 'client' (primary, one per client) vs 'job'
-- (secondary, many per job). Existing tags default to 'job'.
ALTER TABLE public.tags ADD COLUMN IF NOT EXISTS kind text NOT NULL DEFAULT 'job';

-- Primary client tag (client-level sorting) — lives on the client.
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS primary_tag_id bigint;
CREATE INDEX IF NOT EXISTS idx_clients_primary_tag ON public.clients(primary_tag_id);

-- Sales person is a real user (app_users.id), never free text.
ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS sales_user_id bigint;
CREATE INDEX IF NOT EXISTS idx_jobs_sales_user ON public.jobs(sales_user_id);

-- Line items for job-scoped estimates/invoices.
CREATE TABLE IF NOT EXISTS public.job_line_items (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  description text not null default '',
  quantity double precision default 1,
  unit_price double precision default 0,
  amount double precision default 0,
  sort_order integer default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS idx_job_line_items_job ON public.job_line_items(job_id);

-- Note authorship for the notes → notification/email flow.
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS author_user_id bigint;
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS author_name text DEFAULT '';
ALTER TABLE public.notes ADD COLUMN IF NOT EXISTS author_email text DEFAULT '';

-- Per-user notifications: recipient_user_id NULL = visible to everyone.
ALTER TABLE public.notifications ADD COLUMN IF NOT EXISTS recipient_user_id bigint;
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON public.notifications(recipient_user_id);

CREATE TABLE IF NOT EXISTS public.notification_reads (
  notification_id bigint not null references public.notifications(id) on delete cascade,
  user_id bigint not null,
  read_at timestamptz not null default now(),
  primary key (notification_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_notification_reads_user ON public.notification_reads(user_id);

-- RLS is enabled for consistency; the backend connects as the DB owner and
-- enforces authorization in Node, so no policies are required here.
ALTER TABLE public.job_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notification_reads ENABLE ROW LEVEL SECURITY;
