-- ============================================================
-- FULL SUPABASE MIGRATION — Run this in your Supabase SQL Editor
-- Safe to run on an existing database (IF NOT EXISTS / IF NOT EXISTS)
-- ============================================================

-- ============================================================
-- 1. CLIENTS — add missing columns
-- ============================================================
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS scope_of_work text DEFAULT '';
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS job_cost numeric DEFAULT 0;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS amount_paid numeric DEFAULT 0;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS balance numeric DEFAULT 0;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS status text DEFAULT 'Lead';
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS total_due numeric DEFAULT 0;
ALTER TABLE public.clients ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();

-- ============================================================
-- 2. NOTES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.notes (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS idx_notes_client ON public.notes(client_id);

-- ============================================================
-- 3. PAYMENTS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.payments (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  amount numeric not null,
  payment_date timestamptz not null default now()
);
CREATE INDEX IF NOT EXISTS idx_payments_client ON public.payments(client_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON public.payments(payment_date);

-- ============================================================
-- 4. SETTINGS (company profile, email config)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.settings (
  key text PRIMARY KEY,
  value text NOT NULL
);

-- ============================================================
-- 5. FINANCE OVERRIDES (yearly manual overrides)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.finance_overrides (
  year int primary key,
  total_expected numeric default 0,
  total_received numeric default 0,
  total_remaining numeric default 0,
  total_clients int default 0,
  notes text,
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 6. MARGIN TRACKER EXPENSES
-- ============================================================
CREATE TABLE IF NOT EXISTS public.finance_margin_entries (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  client_name text default '',
  category text default 'Misc',
  project text default '',
  invoice_status text default 'Pending',
  amount numeric default 0,
  expense_type text default 'one-time',
  recurring boolean default false,
  expense_date timestamptz not null default now(),
  notes text default '',
  attachment_url text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 7. ROW LEVEL SECURITY — disable for service role access
--    (your backend uses the service role key so RLS won't block it,
--     but enable these if you want to lock down direct client access)
-- ============================================================
-- ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.finance_overrides ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.finance_margin_entries ENABLE ROW LEVEL SECURITY;
